### ISSUE TITLE
Installing Error

### ISSUE THREAD

**Issue by tpharaoh** [SamuelSub/ecommerce#10]
I got the below after:
npm install
npm run dev

 throw new MongooseError('The `uri` parameter to `openUri()` must be a ' +
          ^

MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.

**Comment by SamuelSub** [comment]
That error is because it pulls the MongoDB URI as an environment variable. So if you want you can create your own MongoDB cluster with some dummy data or i can provide you the test data that i am using. So basically the error should be solved by replacing the process.env.Mongo_URI with your own MongoDB URI
